<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-06-27 19:24
=======
# Generated by Django 4.2.2 on 2023-06-27 23:28
>>>>>>> main

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='이미지')),
                ('contentn', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(verbose_name='작성일')),
<<<<<<< HEAD
                ('view_count', models.ImageField(upload_to='', verbose_name='조회수')),
=======
                ('view_count', models.IntegerField(verbose_name='조회수')),
>>>>>>> main
            ],
        ),
    ]
